spring:
  application:
    name: trustex
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=forexDB;trustServerCertificate=true
    username: zehra
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
      javax:
        persistence:
          validation:
            mode: none
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

server:
  port: 9090
